name: CI Pipeline

on:
  push:
    branches:
      - main # This workflow runs when code is pushed to the 'main' branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest # This job will run on an Ubuntu Linux virtual machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to get your code from the repository

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.3' # Or your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest # Install pytest

      - name: Run tests
        run: pytest # Run your pytest tests
